<UI>:  
    MDBoxLayout:
        orientation: 'vertical'
        MDLabel:
            text: "Hellow kivyMD"
            font_style: 'H2'
            halign: 'center'
            #color: "#2ECC71"
            theme_text_color: "Custom"
            text_color: 0,0,1,1
        MDIcon:
            icon: "fingerprint"
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            color: "red"